--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:CVkRFNoaufHuSw4DrmmugQ==$f/OFKC01YQYlty2v2C9tPrWlGtsmj4LPfkgd5NpraeU=:H8mqLOGMY8rX+m6fi+x06si9glN4eq3X9S96o8DDou0=';

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- Database "menu" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: menu; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE menu WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE menu OWNER TO postgres;

\connect menu

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _tables; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public._tables (
    tableid bigint NOT NULL,
    is_done boolean,
    orderid integer,
    totalcost double precision
);


ALTER TABLE public._tables OWNER TO postgres;

--
-- Name: _tables_tableid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public._tables ALTER COLUMN tableid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public._tables_tableid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: additional_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.additional_products (
    prod_id integer NOT NULL,
    mealid integer,
    products character varying(255),
    price double precision
);


ALTER TABLE public.additional_products OWNER TO postgres;

--
-- Name: additional_products_prod_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.additional_products_prod_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.additional_products_prod_id_seq OWNER TO postgres;

--
-- Name: additional_products_prod_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.additional_products_prod_id_seq OWNED BY public.additional_products.prod_id;


--
-- Name: menu_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu_items (
    mealid bigint NOT NULL,
    pictureofmeal character varying(255),
    mealname character varying(255) NOT NULL,
    price double precision NOT NULL,
    mealcontent character varying(255),
    category character varying(255),
    additionalproducts character varying(255),
    meal_id bigint NOT NULL
);


ALTER TABLE public.menu_items OWNER TO postgres;

--
-- Name: menu_items_meal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.menu_items ALTER COLUMN meal_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_items_meal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_items_mealid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.menu_items_mealid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.menu_items_mealid_seq OWNER TO postgres;

--
-- Name: menu_items_mealid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.menu_items_mealid_seq OWNED BY public.menu_items.mealid;


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    orderid bigint NOT NULL,
    tableid integer NOT NULL,
    status character varying(255) NOT NULL,
    totalcost numeric(38,2) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    mealname character varying(255) NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_orderid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.orders_orderid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.orders_orderid_seq OWNER TO postgres;

--
-- Name: orders_orderid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.orders_orderid_seq OWNED BY public.orders.orderid;


--
-- Name: staff; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.staff (
    staffid bigint NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT staff_role_check CHECK (((role)::text = ANY (ARRAY['Kitchen'::text, 'Waiter'::text, 'Manager'::text])))
);


ALTER TABLE public.staff OWNER TO postgres;

--
-- Name: staff_staffid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.staff_staffid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.staff_staffid_seq OWNER TO postgres;

--
-- Name: staff_staffid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.staff_staffid_seq OWNED BY public.staff.staffid;


--
-- Name: additional_products prod_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.additional_products ALTER COLUMN prod_id SET DEFAULT nextval('public.additional_products_prod_id_seq'::regclass);


--
-- Name: menu_items mealid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_items ALTER COLUMN mealid SET DEFAULT nextval('public.menu_items_mealid_seq'::regclass);


--
-- Name: orders orderid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders ALTER COLUMN orderid SET DEFAULT nextval('public.orders_orderid_seq'::regclass);


--
-- Name: staff staffid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.staff ALTER COLUMN staffid SET DEFAULT nextval('public.staff_staffid_seq'::regclass);


--
-- Data for Name: _tables; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public._tables (tableid, is_done, orderid, totalcost) FROM stdin;
\.


--
-- Data for Name: additional_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.additional_products (prod_id, mealid, products, price) FROM stdin;
1	1	Parmesan cheese	1
2	1	Garlic bread	1.5
3	2	Extra sauce	1
4	4	Lemon slice	3
5	4	Ice	0.5
6	3	Vanilla ice cream	3
\.


--
-- Data for Name: menu_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.menu_items (mealid, pictureofmeal, mealname, price, mealcontent, category, additionalproducts, meal_id) FROM stdin;
1	https://www.tamingtwins.com/wp-content/uploads/2025/01/spaghetti-bolognese-10.jpg	Spaghetti Bolognese	12.99	Classic Italian pasta with a rich tomato and beef sauce.	Main Course	Parmesan cheese, Garlic bread	1
3	https://www.allrecipes.com/thmb/zb8muWE6CQ5XjclY_LQ2i-QwxN0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/17981-one-bowl-chocolate-cake-iii-DDMFS-beauty-4x3-d2e182087e4b42a3a281a0a355ea60d1.jpg	Chocolate Cake	5	Rich chocolate cake with ganache topping.	Dessert	Vanilla ice cream	3
2	https://redhousespice.com/wp-content/uploads/2021/12/whole-spring-rolls-and-halved-ones-scaled.jpg	Spring Rolls	6.5	Crispy vegetable rolls served with sweet chili sauce.	Appetizer	Extra sauce	2
4	https://bakingmehungry.com/wp-content/uploads/2024/05/lipton-iced-tea-recipe-8.jpg	Iced Tea	3	Chilled black tea with lemon.	Beverage	Lemon slice, Ice	4
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (orderid, tableid, status, totalcost, createdat, mealname) FROM stdin;
12	55	Finished	13.99	2025-05-15 00:22:03.634097	Spaghetti Bolognese with Parmesan cheese
23	6666	Finished	3.00	2025-05-15 01:20:45.491131	Iced Tea
13	66	Finished	7.50	2025-05-15 00:25:16.00949	Spring Rolls with Extra sauce
10	2	Delivered	14.49	2025-05-15 00:12:31.276933	Spaghetti Bolognese with Garlic bread
4	2	Finished	11.00	2025-05-05 23:47:53.324813	Chocolate Cake with Vanilla ice cream; Iced Tea
3	3	Finished	19.99	2025-05-05 23:08:46.60688	Spaghetti Bolognese with Parmesan cheese; Iced Tea with Lemon slice
5	5	Finished	25.49	2025-05-06 00:03:57.874539	Spaghetti Bolognese with Garlic bread; Chocolate Cake with Vanilla ice cream; Iced Tea
14	66	Finished	7.50	2025-05-15 00:25:27.070038	Spring Rolls with Extra sauce
6	5	Finished	6.00	2025-05-06 00:10:48.00728	Iced Tea with Lemon slice
2	1	Finished	10.00	2025-05-05 23:08:05.694607	Iced Tea with Ice; Spring Rolls
1	1	Finished	19.49	2025-05-05 23:07:33.352122	Chocolate Cake; Spaghetti Bolognese with Garlic bread
24	6666	Finished	6.50	2025-05-15 01:25:13.928869	Spring Rolls
7	1	Finished	27.99	2025-05-06 13:10:47.318509	Spring Rolls with Extra sauce; Spaghetti Bolognese with Garlic bread; Iced Tea with Lemon slice
15	99	Finished	3.50	2025-05-15 00:45:36.021945	Iced Tea with Ice
8	5	Finished	17.49	2025-05-14 23:01:37.649272	Spaghetti Bolognese with Parmesan cheese; Iced Tea with Ice
9	5	Finished	7.50	2025-05-14 23:03:31.463783	Spring Rolls with Extra sauce
25	500	Finished	10.00	2025-05-15 17:05:05.08296	Spring Rolls; Iced Tea with Ice
16	100	Finished	8.00	2025-05-15 00:54:43.216151	Chocolate Cake with Vanilla ice cream
11	9	Finished	13.99	2025-05-15 00:17:02.170512	Spaghetti Bolognese with Parmesan cheese
17	111	Finished	6.50	2025-05-15 00:59:45.426931	Spring Rolls
26	123	Finished	14.49	2025-05-15 17:09:39.872122	Spaghetti Bolognese with Garlic bread
27	4444	Finished	19.49	2025-05-15 18:03:29.461652	Spaghetti Bolognese; Spring Rolls
18	100	Finished	3.00	2025-05-15 01:08:11.502967	Iced Tea
19	200	Finished	6.50	2025-05-15 01:09:32.922679	Spring Rolls
28	1111	Finished	6.50	2025-05-15 18:09:14.929942	Spring Rolls
20	200	Finished	12.99	2025-05-15 01:10:19.267341	Spaghetti Bolognese
29	333	Finished	16.99	2025-05-16 19:58:19.457362	Spaghetti Bolognese with Parmesan cheese; Iced Tea
21	500	Finished	6.50	2025-05-15 01:11:52.431517	Spring Rolls
22	444	Finished	5.00	2025-05-15 01:15:12.867267	Chocolate Cake
\.


--
-- Data for Name: staff; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.staff (staffid, username, password, role, createdat) FROM stdin;
1	manager_1	manager_1	Manager	2025-05-01 00:00:00
2	waiter_1	waiter_1	Waiter	2025-05-01 00:00:00
3	kitchen_1	kitchen_1	Kitchen	2025-05-01 00:00:00
4	waiter_2	waiter_2	Waiter	2025-05-01 00:00:00
\.


--
-- Name: _tables_tableid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public._tables_tableid_seq', 1, false);


--
-- Name: additional_products_prod_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.additional_products_prod_id_seq', 6, true);


--
-- Name: menu_items_meal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.menu_items_meal_id_seq', 4, true);


--
-- Name: menu_items_mealid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.menu_items_mealid_seq', 1, true);


--
-- Name: orders_orderid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_orderid_seq', 29, true);


--
-- Name: staff_staffid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.staff_staffid_seq', 1, false);


--
-- Name: _tables _tables_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public._tables
    ADD CONSTRAINT _tables_pkey PRIMARY KEY (tableid);


--
-- Name: additional_products additional_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.additional_products
    ADD CONSTRAINT additional_products_pkey PRIMARY KEY (prod_id);


--
-- Name: menu_items menu_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_items
    ADD CONSTRAINT menu_items_pkey PRIMARY KEY (mealid);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (orderid);


--
-- Name: staff staff_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_pkey PRIMARY KEY (staffid);


--
-- Name: staff staff_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_username_key UNIQUE (username);


--
-- Name: additional_products additional_products_mealid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.additional_products
    ADD CONSTRAINT additional_products_mealid_fkey FOREIGN KEY (mealid) REFERENCES public.menu_items(mealid) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database cluster dump complete
--

